### ISSUE TITLE
Good resource

### ISSUE THREAD

**Issue by baochi0212** [ToDucThanh/MLOPS-human-pose-estimation#6]
I found your repo really interesting. I learn MLops recently, can you produce a kinda intuitive docs for your repo, for learn to understand your intuition, why use these tools,  why you design like this, what are alternatives for the tool, etc,. instead of just how to run the repo. Really appreciate it!!!

**Comment by ToDucThanh** [comment]
Thank you for your interest in my repo. There are numerous MLOPs tools that can perform the similar functions as mine (versioning, experiment tracking, testing, serving, monitoring, CI/CD, ...). The ones I've gone with are just my personal preferences, and the only rule I have is that they are open source 😄. In my opinion, MLOps resembles a logo game where you blend specialized tools to craft a final design. Throughout this process, you experiment with different tools to ultimately select the ones you feel most comfortable with.

For additional alternatives, you can refer to this link: https://github.com/kelvins/awesome-mlops

**Comment by baochi0212** [comment]
yeah, I actually scan several refs and materials for the MLOps overview and find they apply different tools for stages, and stumble upon your repo. I personally think it'll be great if you also jot down your thought process, which I haven't found in other sources yet. And bit off-optic, which tool you use for the diagram :D

**Comment by ToDucThanh** [comment]
I also read a lot about MLOps articles, and I agree with you that there are many strategies to apply depending on your project needs. I think there are no standards for what you should do or which tools you have to use, yet (or maybe there are some out there, but I don't know 🤷‍♂️). There are no mysteries to my thought process; I simply mix and match tools in my learning process, so it may seem strange :3.
 
About the tools I used for my diagram: https://excalidraw.com./ Icons and images are from Google Images :D
Hope it helps.

**Comment by baochi0212** [comment]
lol nice, after long time working on modeling, I kinda get lost in mlops tools :v, this kinda project really helps alot ;)
